[server]
headless = true
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4b0082"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e2229"
textColor = "#fafafa"

pip install --no-cache-dir sentence-transformers chromadb faiss-cpu
